name = "ModernTemplatePack"
author = "pen787"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05bde5aff2cdf26d21bbaccbdb192c6f7e49d0f551dc68359c0e5ef127725064"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
