name = "ModernTemplatePack"
author = "pen787"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b9992f6094992f57d71b98fbb5b274e9a705dd18db3418aab99feb4124b89c7"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
